version: "3"

services:
  database:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - database-vol:/var/lib/mysql
    networks:
      - back-office
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DATABASE_USER}"]
      interval: 3s
      retries: 24
      start_period: 12s

  backend:
    # image: ghcr.io/thanawat-toktik/toktik-backend:latest
    # build: https://github.com/thanawat-toktik/toktik-backend.git#main
    build: ../toktik-backend/
    environment:
      - DATABASE_HOST=database
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_RAW_ENDPOINT=${S3_RAW_ENDPOINT}
      - S3_REGION=${S3_REGION}
      - MQ_HOSTNAME=queue
      - MQ_PORT=5672
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      database:
        condition: service_healthy
      queue:
        condition: service_healthy
    networks:
      - back-office
      - user-facing
      
  frontend:
    # image: ghcr.io/thanawat-toktik/toktik-frontend:latest
    # build: https://github.com/thanawat-toktik/toktik-frontend.git#main:toktik-frontend
    build: ../toktik-frontend/toktik-frontend/
    depends_on:
      - backend
    networks:
      - user-facing

  proxy:
    image: nginx:stable-alpine-slim
    ports:
      - "8080:80"
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
    networks:
      - user-facing

  queue:
    image: rabbitmq:management-alpine
    networks:
      - back-office
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 3s
      retries: 24
      start_period: 12s

  vid-converter:
    build: ../toktik-vid-convert/
    networks:
      - back-office
    environment:
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_RAW_BUCKET_NAME=${S3_RAW_BUCKET_NAME}
      - S3_CONVERTED_BUCKET_NAME=${S3_CONVERTED_BUCKET_NAME}
      - S3_RAW_ENDPOINT=${S3_RAW_ENDPOINT}
      - S3_REGION=${S3_REGION}
      - MQ_HOSTNAME=queue
      - MQ_PORT=5672
    depends_on:
      queue:
        condition: service_healthy
  queue-check-scheduler:
    build: ../toktik-scheduler/
    networks:
      - back-office
    environment:
      - BACKEND_HOST=backend
      - BACKEND_PORT=8000
    depends_on:
      - backend

networks:
  user-facing:
  back-office:

volumes:
  database-vol:
    driver: local
