apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: toktik-backend
          image: ghcr.io/thanawat-toktik/toktik-backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: SECRET_KEY
            - name: DATABASE_HOST
              value: database
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: DATABASE_NAME
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: DATABASE_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: DATABASE_PASSWORD
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: S3_ACCESS_KEY
            - name: S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: S3_SECRET_ACCESS_KEY
            - name: S3_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: S3_BUCKET_NAME
            - name: S3_RAW_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: S3_RAW_ENDPOINT
            - name: S3_REGION
              value: "us-east-1"
            - name: REDIS_HOSTNAME
              value: queue
            - name: REDIS_PORT
              value: "6379"
      imagePullSecrets:
        - name: ghcr-secret
