apiVersion: apps/v1
kind: Deployment
metadata:
  name: converter
  labels:
    app: converter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: converter
  template:
    metadata:
      labels:
        app: converter
    spec:
      containers:
        - name: toktik-vid-convert
          image: ghcr.io/thanawat-toktik/toktik-vid-convert:latest
          env:
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: converter-secrets
                  key: S3_ACCESS_KEY
            - name: S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: converter-secrets
                  key: S3_SECRET_ACCESS_KEY
            - name: S3_RAW_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: converter-secrets
                  key: S3_RAW_BUCKET_NAME
            - name: S3_CONVERTED_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: converter-secrets
                  key: S3_CONVERTED_BUCKET_NAME
            - name: S3_RAW_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: converter-secrets
                  key: S3_RAW_ENDPOINT
            - name: S3_REGION
              value: "us-east-1"
            - name: REDIS_HOSTNAME
              value: queue
            - name: REDIS_PORT
              value: "6379"
      imagePullSecrets:
        - name: ghcr-secret
