apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: postgres:alpine
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: db_name
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: database-pvc
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["sh", "-c", "pg_isready", "-U", "$POSTGRES_USER"]
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 20
      volumes:
        - name: database-pvc
          persistentVolumeClaim:
            claimName: database-pvc
