apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: toktik-frontend
          image: ghcr.io/thanawat-toktik/toktik-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
          - name: VUE_APP_WS_HOST
            value: notification
          - name: WS_PORT
            value: "3000"
      imagePullSecrets:
        - name: ghcr-secret
