apiVersion: v1
kind: Service
metadata:
  name: notification
  annotations:
    traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
    traefik.ingress.kubernetes.io/service.sticky.cookie.name: cookie
    traefik.ingress.kubernetes.io/service.sticky.cookie.secure: "true"
spec:
  selector:
    app: notification
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
