apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  labels:
    app: notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      initContainers:
        - name: queue-healthcheck
          image: busybox:latest
          command: ["sh", "-c", "until nc -z queue 6379; do sleep 1; done"]
      containers:
        - name: toktik-notifications
          image: ghcr.io/thanawat-toktik/toktik-notifications:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: WS_PORT
              value: "3000"
            - name: REDIS_HOSTNAME
              value: queue
            - name: REDIS_PORT
              value: "6379"
      imagePullSecrets:
        - name: ghcr-secret
